version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    environment:
      - REDIS_PASSWORD=admin
    command:
      [
        "redis-server",
        "--requirepass", "admin",
        "--appendonly", "yes"
      ]
